### ISSUE TITLE
Prevent picking up `python3?`

### ISSUE THREAD

**Issue by FichteFoll** [maximbaz/rebuild-detector#11]
It appears the Python rebuild detector always picks up the packages for the other Python versions, i.e. `python33` and `python37`. There probably needs to be an exception for them.

**Comment by max-baz** [comment]
Could you clarify a bit more what you think is the problem? Right now `python3` is `3.8`, so if you have `/usr/lib/python3.7` folder this most probably means you have to upgrade/rebuild some packages against the latest version 😉

**Comment by FichteFoll** [comment]
I mean this:

```
$ checkrebuild
…
aur	python33
aur	python35
aur	python36
…
```

These packages contain a readme in that folder:

```
λ pacman -F /usr/lib/python3.6/site-packages/README.txt
usr/lib/python3.6/site-packages/README.txt is owned by aur/python36 3.6.8-1
```

**Comment by max-baz** [comment]
Ah, I see - and I assume you don't want to disable python check entirely, you just want these three specific packages to be skipped, correct?

If so, I think the best option for you is to `checkrebuild | grep -v ...` (or create a wrapper script), because it doesn't feel good to hardcode some very specific AUR package names in this tool.

**Comment by FichteFoll** [comment]
I would argue about the "very specific" part, since the rebuild script concers itself about the system Python and these very packages provide different versions of Python. Would excluding packages that provide `/usr/lib/python3.?/README.txt` work?

**Comment by max-baz** [comment]
Isn't it likely that if you have a different python installed, you will also have at least one python package installed for this version of python? In other words, `/usr/lib/python3.7` folder would contain not only `README.txt` but also something else?

**Comment by FichteFoll** [comment]
Personally, I don't because I have them for tox and otherwise only use them in virtualenvs.

**Comment by max-baz** [comment]
Right now I still have an impression that this is too specific to your own setup... 🤔 

Python check (as well as perl and ruby and haskell now) are there to help users notice that system version got upgraded, but if you keep several older versions installed on purpose, you have to filter out the results depending on your use-case (in your specific case, you can filter out only `python3\d`)

Just like with aurutils, treat this little script as something you can build upon for your own amazing setup 😉

**Comment by FichteFoll** [comment]
Well, if you believe this is too special of a use case, I'm fine with excluding these with a script or from the shell, but the upgrade hook is really convenient and I can't update that (or the script it references) in-place without imposing a conflict on updates. Any recommendations for that or should I just run my own hook?

Edit: Actually, the hook takes way too much time to run anyway, so I'll disable it.

**Comment by max-baz** [comment]
Starting from `4.1.0` the hook runs only against direct dependencies of packages that are being updated, so for example if you update `python-jsonrpc-server`, the hook will only check if `python-language-server` needs to be rebuilt. This alone probably will already help you, as it will almost never show those alternative python packages.

But you said that hook runs forever for you? On `4.1.0`? Is this a regression, or you don't really know how it was before? I would be interested to understand why it takes so long for you.

**Comment by FichteFoll** [comment]
No, I was running 4.0.0 still, which did a full pass and took 10s to run. Now the hook's runtime is barely noticeable (and full pass is down to 8s).

**Comment by max-baz** [comment]
Awesome 👍 

I wasn't entirely correct though in my example above, python packages are checked fully even in the hook, I clarified that in readme. 

Let me know if you have some ideas on how I can make it easier to build upon this script. Wondering for example if in the hook I should remove the full path to checkrebuild, so that you can create a wrapper script, put it higher in your $PATH and get it executed instead.

**Comment by FichteFoll** [comment]
If that is a possibility, it might be worth exploring that so that users can strip the output of this script in a way they see fit. While using env would certainly be able to workaround a requirement for a full paths in hooks, assuming arguments are possible, I worry if this could have security implications since it appears hooks are run as root and it might be possible to inject a malicious executable somewhere earlier on the PATH.

**Comment by max-baz** [comment]
Good point about security concerns 🤔

**Comment by FichteFoll** [comment]
> if you keep several older versions installed on purpose, you have to filter out the results depending on your use-case (in your specific case, you can filter out only `python3\d`)

I have a good example against this. The builds I had were outdated because of a soname change of `libffi`, but I didn't recognize this because I always see these packages as "needing a rebuild".

As I mentioned before, I keep older python versions (which are still maintained) around so I can run tests with them for my packages. I don't have a system package installed that depends on them (and [there aren't many on the AUR that require them either](https://aur.archlinux.org/packages/python37/), since most packages would require just `python`) and I still intend to use them as-is. The packages themselves aren't outdated as they still have uses. The proper procedure to detect those as outdated would be when they are missing from the AUR. 

Thus, I believe the rebuild-detector should be adjusted to care for them. My recommendation would be to just exclude packages with pinned python versions in their name, i.e. packages matching `python3{1..9}`, from the `/usr/lib/python3.?` check, since they are intended to go there.

**Comment by max-baz** [comment]
Hey! Would it really solve the issue in the example you mentioned? If we exclude old python packages, then they would not show up even if soname changed in `libffi`?

**Comment by FichteFoll** [comment]
I'm not sure I understand the question, but let me try: Old Python packages should only be excluded for the "is this packaged for an older version of python" check, not for the linked library check. Since this logic is contained within the script, it should be done from within as the outside can't distinguish what check the reported package came from.

**Comment by max-baz** [comment]
I see, yes you have answered my question 👍 OK so do I understand correctly, that your wish will be granted if we change this line:

https://github.com/maximbaz/rebuild-detector/blob/4d039d15875c12997b3fc8d8a825d9bd8b8e018b/checkrebuild#L66

to:

```diff
-pacman -Qqo /usr/lib/python3.!("$python_version") 2>/dev/null
+pacman -Qqo /usr/lib/python3.!("$python_version") 2>/dev/null | grep -v '^python3[0-9]'
```

Could you please try this locally and see if it resolves the issue for you?

**Comment by FichteFoll** [comment]
Positive. It only showed `python33` on a test run with that change, which I assume is due to a legit soname change without checking that.
