### ISSUE TITLE
Incorrect Link on main page, please update

### ISSUE THREAD

**Issue by Scotty-Trees** [maximbaz/rebuild-detector#17]
Greetings,

On the main Github page https://github.com/maximbaz/rebuild-detector under the heading "Installation" it provides a link to the AUR package of rebuild-detector. However, rebuild-detector is now provided by the Arch official community repos, so the correct link for installation would be here: https://archlinux.org/packages/community/any/rebuild-detector/

Please feel free to update the links at your earliest convenience. It's not a big deal, just something I noticed since it's no longer in the AUR. And thanks for making a great little piece of software, I haven't used it yet, but a new release of python is dropping soon, so I'm sure I'll have some rebuilds coming up soon enough!

**Comment by max-baz** [comment]
Thanks, fixed 🙂

**Comment by Scotty-Trees** [comment]
That was a fast fix! And you're very welcome. Enjoy the rest of your weekend :)
