### ISSUE TITLE
checkrebuild ldd reports library in uninstalled optdepend as requiring rebuild

### ISSUE THREAD

**Issue by LW-archlinux** [maximbaz/rebuild-detector#18]
My aur mesa-minimal-git[1] has an optdepend on llvm-minimal-git[2] .
 
```
$ checkrebuild -v
lonewolf        mesa-minimal-git

ldd /usr/lib/libMesaOpenCL.so.1.0.0

        libclang-cpp.so.14 => not found
$
```

That file comes from the llvm-minimal-git package, which is present in my lonewolf repo .
Installing that optional dependency solves the issue withourt needing a rebuild .

maybe checkrebuild can use pacman -F or pkgfile to verify whether a missing file requires a rebuild or is just uninstalled ?

Lone_Wolf

P.S. nice utility, it did alert me to 2 necessary rebuilds for other packages.

[1] https://aur.archlinux.org/packages/mesa-minimal-git
[2] https://aur.archlinux.org/packages/llvm-minimal-git/

**Comment by max-baz** [comment]
Hello, thanks for the feedback 🙂 I'd prefer to not distinguish potential causes, and just flag the package if it misses a dependency for whatever reason. Is it actually possible that in your particular case the dependency is not optional, but is required in that case, as it's linked against it?

By the way, if the package is falsely marked and you periodically monitor the output of `checkrebuild`, you can also filter out it using e.g. `checkrebuild | grep -v mesa-minimal-git`.

**Comment by LW-archlinux** [comment]
The main reason it's done that way is to reduce conflicts between my llvm-minimal  packages and repo llvm/clang .
I'll investigate changing how I pacakge llvm-minimal, but that doesn't solve the underlying discrepanncy I noticed .

Trying to rephrase the issue.

Rebuild-detector doesn't appear to have a man page or other documentation, so the project name , scriptname and readme file are what users will look at for documentation 

All those indicate detection of older linraries requiring a rebuild is the goal.

I ran the tool and saw to my sirrpise it listed a package which I **knew** doesn't require a rebuild.
My immediate feeling was "the tool is faulty" .

Further investigation made clearer what caused the report and I created this issue.

Maybe the readme can be changed to make clear(er) some outputted packages could be false positives and need other solutions then rebuilding .

**Comment by max-baz** [comment]
This makes a lot of sense to me, will do!

**Comment by max-baz** [comment]
I actually couldn't think of what else to add to this section of readme: https://github.com/maximbaz/rebuild-detector#what-do-i-do-if-a-package-is-flagged

Do you have some suggestions, how to make it clearer?

**Comment by LW-archlinux** [comment]
The section itself is indeed clear, it just needs to stand out more .

Maybe indent the list of supported checks to the right and add a note above it ?

Something like 

**NOTE:** False positives can and will occur . Check https://github.com/maximbaz/rebuild-detector#what-do-i-do-if-a-package-is-flagged _**before starting any rebuild**_.

**Comment by max-baz** [comment]
Thanks for the suggestion, and for confirming that the docs are clear. 

I prefer not to do this, as rebuild is still far more frequent reason than a package that forgot to specify a dependency. Rebuild is also not _too bad_ to do, I wouldn't like to warn against it, personally I'd run a rebuild anyway, and start investigating a false positive if and only if rebuild didn't help 🙂 

Getting README content packaged into a man-page as you suggested is certainly something I'd like to have, as then these caveats would not require anyone to go to Github to find. A PR would definitely be appreciated as I don't think I'll have time to look into this in a near future - if you or anyone else wants to volunteer, just shoot me a PR 🙂
