### ISSUE TITLE
Latest release excludes AUR packages from being checked

### ISSUE THREAD

**Issue by lectrode** [maximbaz/rebuild-detector#20]
Is there a way to check AUR packages with the latest release? The latest [commit](https://github.com/maximbaz/rebuild-detector/commit/c29f3c138425664174c46e06add432fcc149c150) seems to specifically filter out any foreign packages.

**Comment by max-baz** [comment]
Hello, that was certainly not the goal, could you help debugging this? I assume in previous version AUR packages were reported for you as "foreign"? Could you undo the changes bit by bit to narrow down where the error is? Is it reproducible for example if you undo changes only in `filter_packages_by_repos`?

**Comment by max-baz** [comment]
Ooh maybe I see what went wrong in my logic - what if you change the value inside quotes to be "foreign", does it help? 

https://github.com/maximbaz/rebuild-detector/blob/c29f3c138425664174c46e06add432fcc149c150/checkrebuild#L30

**Comment by lectrode** [comment]
changing it to "foreign" makes no difference. as a note: `pacman -Sl` does not list any foreign packages, even without arguments. If you're using that as a basis for a "whitelist" of packages to check, it will never check foreign/aur packages.

If I'm reading those changes correctly, that went from an exclusion list to an inclusion list, correct?

**Comment by lectrode** [comment]
If you want to include foreign packages, you'd have to list those separately, with something like: `pacman -Qqm`

**Comment by max-baz** [comment]
Right, you are correct on every point, it's clear now what to fix, thanks - I'll push something once I'm at laptop tomorrow and will ping you to verify. Many thanks for bringing this up!

**Comment by max-baz** [comment]
Hello, please test the code in master 🙂

**Comment by lectrode** [comment]
looks good! thx for getting to this so quickly!

**Comment by max-baz** [comment]
4.3.0 released 🚀
