### ISSUE TITLE
Pacman -S  rebuild-detector error

### ISSUE THREAD

**Issue by bzhmaddog** [maximbaz/rebuild-detector#25]
parallel-20220522-1-any.pkg.tar.zst failed to download

error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.osbeck.com : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from archlinux.mailtunnel.eu : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from archlinux.uk.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from ftp.halifax.rwth-aachen.de : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from archmirror.it : The requested URL returned error: 403
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from arch.jensgutermuth.de : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.wtnet.de : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.chaoticum.net : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.f4st.host : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from phinau.de : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.telepoint.bg : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from archlinux.thaller.ws : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from arch.mirror.square-r00t.net : Failed to connect to arch.mirror.square-r00t.net port 443 after 5267 ms: Connection timed out
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from arch.mirror.constant.com : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.hackingand.coffee : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirror.lty.me : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from archlinux.za.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from asia.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'parallel-20220522-1-any.pkg.tar.zst' from mirrors.neusoft.edu.cn : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.

**Comment by max-baz** [comment]
I feel like you are trying [a partial update, which is unsupported](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported). The latest version of parallel is [2022-10-22](https://archlinux.org/packages/community/any/parallel/).

**Comment by bzhmaddog** [comment]
Hmm.
I simply followed the instruction given on the Readme page. Should I try to install 'parallel' manually ?

**Comment by max-baz** [comment]
Run a system update first, before installing a new package, `pacman -Syu`

**Comment by bzhmaddog** [comment]
Well that's a weird statement imo. Why should my system be up to date in order to install a package ? Except if the package I am trying to install depends on a version of a package that is more recent than the one installed.
I have read on multiple sources that there was an issue with OpenSSL3 currently and that updating would cause chaos. That why I am trying to install this package. Anyways I'll find a solution

**Comment by max-baz** [comment]
In your specific example, your system thinks that the latest `parallel` is of version `20220522` (which it isn't anymore, it's an old version), so it tries to find such specific version on various mirrors, but this old version is already gone from all mirrors, so your system can't find it, and aborts.

**Comment by bzhmaddog** [comment]
Indeed after updating my system (which was a bit problematic due to some expired keys) I managed to install the package
