### ISSUE TITLE
Skip Hook During Install

### ISSUE THREAD

**Issue by stef204** [maximbaz/rebuild-detector#29]
I do not want the hook running as I prefer to run `rebuild-detector` manually.  I can't quite figure out how to modify source code to have it NOT install the hook in `/usr/share/libalpm/hooks`. (I could always comment out all the lines of the hook file but that's kind of ugly.)

Can you please explain how to skip the hook install?

**Comment by max-baz** [comment]
I think what you are looking for is to comment out this line:

https://github.com/maximbaz/rebuild-detector/blob/0fbc3295af697f0f98d414f3a3010c679e60f6fc/Makefile#L34

**Comment by stef204** [comment]
~~That's the problem: I have commented it out, but it still installs the hook.... I've even tried to remove line 34 altogether and it still installs the hook...which is why I posted here....~~

EDIT: My mistake: I forgot to use the `-e` with `makepkg`.

Let's close this.

**Comment by max-baz** [comment]
Happy to see you resolved it :+1:
