### ISSUE TITLE
'Argument list too long' error if 'checkrebuild -v' output is large

### ISSUE THREAD

**Issue by drws** [maximbaz/rebuild-detector#34]
Currently there are two packages with many dependencies in need of a rebuild in a system I use. If `checkrebuild -v` is ran, an error is encountered:

`environment: /usr/bin/c++filt: Argument list too long`

The order of magnitude is 200k lines of output - since apparently that's how it is with some software packages. Please also see [a relevant SO thread](https://stackoverflow.com/questions/57251024/exact-limit-to-avoid-argument-list-too-long). Apparently something gets overloaded with arguments somewhere along the way.

**Comment by max-baz** [comment]
Thanks for the report - would you be able to test https://github.com/maximbaz/rebuild-detector/commit/da360220725870047073a9a7c11c6ab6d2e22693 ?

**Comment by drws** [comment]
Confirming it works as expected with the fix. Thank you for a very quick solution!

**Comment by max-baz** [comment]
Fantastic, thanks for confirming!
